---
- name: install catalogs
  shell: ideascube catalog remotes add "{{ item.id }}" "{{ item.name }}" "{{ item.url }}"
  with_items: "{{ catalogs[env] }}"

- name: update ideascube cache
  shell: ideascube catalog cache update

- name: Download and make a local copy of each catalog
  get_url:
    url: "{{ item.url }}"
    dest: "/tmp/{{ item.id }}.yaml"
    mode: 0644
  with_items: "{{ catalogs[env] }}"

- name: Load all catalogs as ansible vars
  include_vars:
    file: "/tmp/{{ item.id }}.yaml"
    name: "{{ item.id }}"
  with_items: "{{ catalogs[env] }}"

- name: include tasks for deployable image
  include_tasks: deployable.yml
  when: 
  - deployable is defined
  - deployable|bool == true

- name: include tasks for non-deployable image
  include_tasks: non-deployable.yml
  when:
  - deployable is defined
  - deployable|bool == false

- name: Download Kiwix binary
  get_url:
    url: http://filer.bsf-intranet.org/kiwix-manage-x86_64
    dest: /usr/local/bin/kiwix-manage
    mode: 0755

- name: Gather all package names for device
  set_fact:
    device_pkg_list: "{{ ansible_local.device_list[generic_project_name].package_management | map(attribute='name') |list }}"

- name: Extract list of Kiwix packages to install.
  set_fact:
    device_kiwix_pkg: "{{ Kiwix.all.keys() | intersect(device_pkg_list) }}"

- name: Try to link kiwix packages without installing.
  block:
    - file: path=/var/ideascube/kiwix/data/{{ item }} state=directory mode=0755
      with_items:
        - "content"
        - "library"
        - "index"
    - shell: |
        ln -s /mnt/kiwix{{ Kiwix.all[item]['url'].split("download.kiwix.org")[-1] }} /var/ideascube/kiwix/{{ item }}.zim
        kiwix-manage /var/ideascube/kiwix/library.xml add /var/ideascube/kiwix/{{ item }}.zim
      with_items: "{{ device_kiwix_pkg }}"
      notify: Start kiwix serve
      ignore_errors: True
    - include_vars: file=/var/ideascube/main/catalog/installed.json name="installed_json"
    - set_fact:
        installed_json: "{{ installed_json | combine({ item: Kiwix['all'][item] }) }}"
      with_items: "{{ device_kiwix_pkg }}"
    - copy: content="{{ installed_json | to_nice_json }}"  dest=/var/ideascube/main/catalog/installed.json
    - script: update_sqlite.py "{{ device_kiwix_pkg |join(' ')}}"
  rescue:
    - debug: msg="Failed updating Ideascube after kiwix packages installations, error could be with installed.json or default.sqlite."
