---
- name: Gather project content from API
  uri:
    url: "{{API[env]}}{{project_id}}"
    body_format: json
    register: omeka

- name: print file path
  debug:
    msg: {{ item.path }}
  with_items: {{ omeka.json.content.items }}

