---
- name: Gather project content from API
  uri:
    url: "{{API[env]}}{{project_id}}"
    body_format: json
  register: omeka

- name: Create media folders
  file:
    dest: "/var/ideascube/mediacenter/{{ item.slug }}/files/original"
    state: directory
    mode: '0755'
  with_items:
    - "{{ omeka.json.content }}"

- name: Create symlinks
  file:
    src: "/mnt/alexandrie/{{ item.1['path']}}"
    dest: "/var/ideascube/mediacenter/{{ item.0.slug }}/{{ item.1.path}}"
    state: link
  with_subelements:
    - "{{ omeka.json.content }}"
    - items

- name: Create another media folder
  file:
    dest: "/var/ideascube/main/media"
    state: directory
    mode: '0755'

- name: Create symlinks to this folder
  file:
    src: "/var/ideascube/mediacenter"
    dest: "/var/ideascube/main/media/catalog"
    state: link

- name: Install python dependencies
  pip:
    name:
      - SQLAlchemy==1.3.8
      - Unidecode==1.1.1
      - requests==2.21.0
      - PyYAML==5.1.2
    executable: pip3

- name: Update default.sqlite
  script: spoof_packages_install.py "{{API[env]}}{{project_id}}"


