---
- name: Gather project content from API
  uri:
    url: "{{API[env]}}{{project_id}}"
    body_format: json
    register: omeka

- name: Create media folders
  file:
    dest: "/var/ideascube/mediacenter/{{ item.slug }}/files/original"
    state: directory
    mode: '0755'
  with_items:
    - "{{ omeka.json.content }}"

- name: create symlinks
  file:
    src: "/mnt/alexandrie/{{ item.1['path']}}"
    dest: "/var/ideascube/mediacenterpkgs/{{ item.0.slug }}/{{ item.1.path}}"
    state: link
  with_subelements:
    - "{{ omeka.json.content }}"
    - items

- name: Install apt dependencies
  apt:
    name: pip3

- name: Install python dependencies
  pip:
    - SQLAlchemy==1.3.8
    - Unidecode==1.1.1
    - requests==2.22.0
  executable: pip3

- name: Update default.sqlite
  script: spoof_packages_install.py "{{API[env]}}{{project_id}}"


