---
- name: Get device_list
  get_url:
    url: https://raw.githubusercontent.com/ideascube/ansiblecube/oneUpdateFile/roles/set_custom_fact/files/device_list.fact
    dest: /etc/ansible/facts.d/device_list.fact
    mode: 0644

- name: reload ansible_local
  setup: filter=ansible_local

- name: Copy hosts entries
  copy:
    src: hosts
    dest: /tmp/hosts
    mode: 0644

- name: Spoof DNS entries
  shell: cat /tmp/hosts >> /etc/hosts

- name: set nginx vhost for ideascube
  template:
    src: ideascube.vhost.j2
    dest: /etc/nginx/sites-enabled/ideascube

- name: set nginx vhost for kiwix
  template:
    src: kiwix.vhost.j2
    dest: /etc/nginx/sites-enabled/kiwix

- name: set long domain name in nginx
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "# server_names_hash_bucket_size"
    line: server_names_hash_bucket_size 128;

- name: start nginx
  service: 
    name: nginx
    state: started
