---
- name: Get device_list
  get_url:
    url: https://raw.githubusercontent.com/ideascube/ansiblecube/oneUpdateFile/roles/set_custom_fact/files/device_list.fact
    dest: /etc/ansible/facts.d/device_list.fact
    mode: 0644

- name: reload ansible_local
  setup: filter=ansible_local

- name: set nginx vhost
  template:
    src: ideascube.vhost.j2
    dest: /etc/nginx/sites-enabled/ideascube

- name: start nginx
  service: nginx
  state: started
