---
- name: Create a working dir kolibri
  become: yes
  become_user: ideascube
  file: path=/home/ideascube/.kolibri state=directory

- name: Install Kolibri in virtualenv
  become: yes
  become_user: ideascube
  pip: 
    version={{ ansible_local.device_list[generic_project_name].kolibri.version }}
    name=kolibri
    chdir=/home/ideascube/.kolibri
    virtualenv=/home/ideascube/.kolibri/env

- name: Create a symlink for Kolibri vhost to Nginx-enabled folder
  file:
    src: /etc/nginx/sites-available/kolibri
    dest: /etc/nginx/sites-enabled/kolibri
    state: link
    force: yes

- name: Start Kolibri
  become: yes
  become_user: ideascube
  shell: /home/ideascube/.kolibri/env/bin/python2 /home/ideascube/.kolibri/env/bin/kolibri start

- name: Import Kolibri content if we are at BSF
  include: import_content.yml
