---
- name: Install few necessary packages for this role
  apt: name={{ item }} state=present
  with_items:
    - cifs-utils

- name: Create a working dir kolibri
  file: path=/root/.kolibri state=directory

- name: Install Kolibri in virtualenv
  pip: 
    version={{ ansible_local.device_list[generic_project_name].kolibri.version }}
    name=kolibri
    chdir=/root/.kolibri
    virtualenv=/root/.kolibri/env

- name: Create a symlink for Kolibri vhost to Nginx-enabled folder
  file:
    src: /etc/nginx/sites-available/kolibri
    dest: /etc/nginx/sites-enabled/kolibri
    state: link
    force: yes

- name: Start Kolibri
  shell: /root/.kolibri/env/bin/python2 /root/.kolibri/env/bin/kolibri start

- name: Import Kolibri content if we are at BSF
  include: import_content.yml
